global:

  scrape_interval: 15s

  evaluation_interval: 15s

scrape_configs:

  - job_name: 'prometheus'

    static_configs:

    - targets: ['192.168.xx.xx:9090']

      labels:

        alias: 'prometheus'

  - job_name: 'cadvisor'

    static_configs:

    - targets: ['192.168.xx.xx:8088']

      labels:

        alias: 'cadvisor'

  - job_name: 'node-exporter'

    static_configs:

    - targets: ['192.168.xx.xx:9100']

      labels:

        alias: 'node-exporter'
