version: "3"

networks:
  operation:
    external: true

services:
  loki:
    image: grafana/loki:2.4.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - operation
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.78.32:3100/loki/api/v1/push"

  promtail:
    image: grafana/promtail:2.4.0
    volumes:
      - /var/log:/var/log
      - ${PWD}/loki/config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    ports:
      - "1514:1514"
    networks:
      - operation
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.78.32:3100/loki/api/v1/push"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - operation
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.78.32:3100/loki/api/v1/push"

  cadvisor:
    image: 'google/cadvisor:latest'
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8088:8080'
    networks:
      - operation
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.78.32:3100/loki/api/v1/push"

  node-exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'
    networks:
      - operation
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.78.32:3100/loki/api/v1/push"

  prometheus:
    image: prom/prometheus
    volumes:
      - ${PWD}/prometheus/config.yaml:/etc/prometheus/prometheus.yml
    ports:
      -  '9090:9090'
    networks:
      - operation
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.78.32:3100/loki/api/v1/push"

  


  

