version: '3'

networks:
  operation:
    external: True

services:
  syslog-ng:
    image: balabit/syslog-ng:latest
    ports:
      - "514:514/udp"
    volumes:
      - ${PWD}/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
      - /var/docker-log:/data/syslog
    networks:  
      - operation