---
 - name: Add Users
   hosts: ops
   tasks:
   - debug:
       msg: "Working on Hostname:{ {{ inventory_hostname }} } Distribution:{ {{ ansible_distribution }} {{ ansible_distribution_version }} } Operation Time:{ {{ ansible_date_time.date }} {{ ansible_date_time.time }} {{ ansible_date_time.tz }} }"
   - debug:
       msg: "Hostname:{ {{ inventory_hostname }} } IPAddr:{ {{ ansible_all_ipv4_addresses }} } Gateway:{ {{ ansible_default_ipv4.gateway }} }"
     when:
       - ansible_default_ipv4.gateway is defined
       - ansible_all_ipv4_addresses is defined

   - name: Ensure group "support"
     group:
       name: support
       state: present
       gid: 1111

   - name: Add Support users
     user:
       name: support
       uid: 1111
       comment: Globals user suppport team
       shell: /bin/bash
       groups: support,docker
       expires: -1
       update_password: always
       #password: $6$ZD7peuJCxWoWM/JJ$cXohqyydMm8vSD1Y61L.ZimZXTnXdKxJKA.ZHuM7QhT8QNUcbJcwUzFBbssuZ.F9kYjdWo/Q1VYZgdOcJCea10
       password: $6$8g/EDM.iEAsYZtn5$H/FHlp9aTcD3wW8TYqVLwzqb7JwwFSSamQXfPu2yPjgwxAcbPUetDbslvZa0i71tdJZ8J7QUmYtMv/Ml8u5ve.


       