---
 - name: Disable disable
   hosts: ops
   tasks:
   - debug:
       msg: "Working on Hostname:{ {{ inventory_hostname }} } Distribution:{ {{ ansible_distribution }} {{ ansible_distribution_version }} } Operation Time:{ {{ ansible_date_time.date }} {{ ansible_date_time.time }} {{ ansible_date_time.tz }} }"
   - debug:
       msg: "Hostname:{ {{ inventory_hostname }} } IPAddr:{ {{ ansible_all_ipv4_addresses }} } Gateway:{ {{ ansible_default_ipv4.gateway }} }"
     when:
       - ansible_default_ipv4.gateway is defined
       - ansible_all_ipv4_addresses is defined
       
   - name: sysctl disable ipv6
     sysctl:
       name: "{{ item }}"
       state: present
       value: 1
       sysctl_file: /etc/sysctl.conf
       reload: yes
     loop:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.lo.disable_ipv6
        - net.ipv6.conf.ens160.disable_ipv6