version: "3"

networks:
  operation:
    external: true

services:
  loki:
    image: grafana/loki:2.4.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - operation

  promtail:
    image: grafana/promtail:2.4.0
    volumes:
      - /var/log:/var/log
      - ${PWD}/config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    ports:
      - "1514:1514"
    networks:
      - operation

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - operation
