version: '3'

networks:
  workload:
    external: true

services:
  web:
    image: nginx
    restart: always
    ports:
      - "8080:80"
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://192.168.62.42:514"
        tag: nginx
    networks:
      - workload
  web2:
    image: nginx
    restart: always
    ports:
      - "8081:80"
    logging:
      driver: "loki"
      options:
         loki-url: "http://192.168.62.42:3100/loki/api/v1/push"
    networks:
      - workload