version: '3'
services:
  guacd:
    image: guacamole/guacd
    restart: unless-stopped
    ports:
      - 4822:4822
    networks:
      - operation
    logging:
      driver: "loki"
      options:
         loki-url: "http://support:3100/loki/api/v1/push"
  guacamole:
    image: guacamole/guacamole
    restart: unless-stopped
    environment:
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
      MYSQL_HOSTNAME: db
      MYSQL_DATABASE: guacamole
      MYSQL_USER: dbadmin
      MYSQL_PASSWORD: P@ssw0rd
    ports:
      - 8080:8080
    networks:
      - operation
    logging:
      driver: "loki"
      options:
         loki-url: "http://support:3100/loki/api/v1/push"
    links:
      - "guacd"
      - "db"
  db:
    image: mariadb
    restart: unless-stopped
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MARIADB_ROOT_PASSWORD: P@ssw0rd
      MARIADB_USER: dbadmin
      MARIADB_PASSWORD: P@ssw0rd
      MARIADB_DATABASE: guacamole
    volumes:
      - db_data:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d
    networks:
      - operation
    expose:
      - 3306
    logging:
      driver: "loki"
      options:
         loki-url: "http://support:3100/loki/api/v1/push"

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOSTS=db
    ports:
      - 8866:80
    networks:
      - operation
    links:
      - "db"
    logging:
      driver: "loki"
      options:
        loki-url: "http://support:3100/loki/api/v1/push"

volumes:
  db_data: 

networks:
  operation:
    external: true